language: node_js
node_js: '8'

cache:
  yarn: true

install:
  - yarn --frozen-lockfile --non-interactive

stages:
  - name: test
    if: (tag IS blank) OR (type != push) OR (repo != vuetifyjs/vuetify)

jobs:
  include:
    - stage: test
      before_script:
        - npm i codecov -g
      script:
        - lerna run lint
        - lerna run test:coverage -- -i
      after_script:
        - codecov

    - stage: test
      script: lerna run build
