language: node_js
node_js:
  - "8"

before_script:
  - npm i codecov -g

script:
  - yarn --frozen-lockfile --non-interactive
  - yarn run lint
  - yarn run test:coverage && codecov
  - yarn run build

cache:
  yarn: true

before_deploy:
  - rm -rf release
  - mkdir -p release
  - for file in ./dist/*; do cp "$file" "${file/dist\/vuetify/release/vuetify-${TRAVIS_TAG}}"; done
  - zip -jr "release/vuetify-${TRAVIS_TAG}.zip" release/*

deploy:
  - provider: npm
    email: "john.j.leider@gmail.com"
    api_key: $NPM_API_KEY
    tag: $(node ./build/parse-npm-tag.js ${TRAVIS_TAG})
    skip_cleanup: true
    on:
      repo: vuetifyjs/vuetify
      tags: true
  - provider: releases
    api_key: $GITHUB_API_KEY
    file: "release/vuetify-${TRAVIS_TAG}.zip"
    skip_cleanup: true
    on:
      tags: true
