project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
project_identifier: vuetify
preserve_hierarchy: true
files:
  - source: packages/api-generator/src/locale/en/**/*.json
    translation: packages/api-generator/src/locale/%locale%/**/%original_file_name%
  - source: packages/docs/src/pages/en/**/*.md
    translation: packages/docs/src/pages/%locale%/**/%original_file_name%
  - source: packages/docs/src/i18n/messages/en.json
    translation: packages/docs/src/i18n/messages/%locale%.json
