"project_identifier": "vuetify"
"api_key_env": CROWDIN_API_KEY
"base_path_env": CROWDIN_BASE_PATH
"preserve_hierarchy": true
"files": [
  {
    "source": "en\\**\\*.json",
    "translation": "%locale%\\**\\%original_file_name%",
  }
]
