name: Vercel Deploy
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
  CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
  CROWDIN_BRANCH: docs-next
  LOCAL_BRANCH: docs/update-from-crowdin

jobs:
  deploy-to-vercel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download eo-UY
        uses: crowdin/github-action@1.0.9
        with:
          config: crowdin.yml
          upload_sources: false
          download_translations: true
          push_translations: false
          export_only_approved: true
          download_language: eo
          localization_branch_name: ${{ env.LOCAL_BRANCH }}
          crowdin_branch_name: ${{ env.CROWDIN_BRANCH }}

      - name: Download de-DE
        uses: crowdin/github-action@1.0.9
        with:
          config: crowdin.yml
          upload_sources: false
          download_translations: true
          push_translations: false
          export_only_approved: true
          download_language: de
          localization_branch_name: ${{ env.LOCAL_BRANCH }}
          crowdin_branch_name: ${{ env.CROWDIN_BRANCH }}

      - name: Download fr-FR
        uses: crowdin/github-action@1.0.9
        with:
          config: crowdin.yml
          upload_sources: false
          download_translations: true
          push_translations: false
          export_only_approved: true
          download_language: fr
          localization_branch_name: ${{ env.LOCAL_BRANCH }}
          crowdin_branch_name: ${{ env.CROWDIN_BRANCH }}

      - name: Download ru-RU
        uses: crowdin/github-action@1.0.9
        with:
          config: crowdin.yml
          upload_sources: false
          download_translations: true
          push_translations: false
          export_only_approved: true
          download_language: ru
          localization_branch_name: ${{ env.LOCAL_BRANCH }}
          crowdin_branch_name: ${{ env.CROWDIN_BRANCH }}

      - name: Download zh-CN
        uses: crowdin/github-action@1.0.9
        with:
          config: crowdin.yml
          upload_sources: false
          download_translations: true
          push_translations: false
          export_only_approved: true
          download_language: zh-CN
          localization_branch_name: ${{ env.LOCAL_BRANCH }}
          crowdin_branch_name: ${{ env.CROWDIN_BRANCH }}

      - name: Download ko-KR
        uses: crowdin/github-action@1.0.9
        with:
          config: crowdin.yml
          upload_sources: false
          download_translations: true
          push_translations: false
          export_only_approved: true
          download_language: ko
          localization_branch_name: ${{ env.LOCAL_BRANCH }}
          crowdin_branch_name: ${{ env.CROWDIN_BRANCH }}

      - name: Download ja-JP
        uses: crowdin/github-action@1.0.9
        with:
          config: crowdin.yml
          upload_sources: false
          download_translations: true
          export_only_approved: true
          push_translations: false
          download_language: ja
          localization_branch_name: ${{ env.LOCAL_BRANCH }}
          crowdin_branch_name: ${{ env.CROWDIN_BRANCH }}

      - name: deploy-to-vercel
        uses: amondnet/vercel-action@v19.0.1+1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod'
          scope: ${{ secrets.VERCEL_ORG_ID }}
          github-comment: false
